### ISSUE TITLE
Renaming info modules in the netapp.um_info collection

### ISSUE THREAD

**Issue by tadeboro** [ansible-collections/netapp#107]
While we were discussing the inclusion of the `netapp.um_info`, we decided that it can be included in Ansible 4.0.0, but we expect the modules to be renamed to _info in time for Ansible 4.1.0. This means this has to be in a minor release by 2021-06-08.

References:

  * The vote comment: https://github.com/ansible-community/community-topics/issues/10#issuecomment-828710569
  * The inclusion request comment: https://github.com/ansible-collections/ansible-inclusion/discussions/18#discussioncomment-646786

**Comment by carchi8py** [comment]
@felixfontein , @tadeboro 

OK i'm in the middle of renaming the modules, @felixfontein i followed what you mentioned in the inclusion thread. 

- I renamed the modules (na_um_aggregates_info)
- i symlinked the old name to the new names
- And i added a quick check to see if they are using the old name/vs new name and give them a deprecated warning if they use the old module Following the example i found here https://github.com/ansible-collections/community.crypto/blob/201920d161fb68dc83de8d37e5b832092b135c42/plugins/modules/acme_account_info.py#L285

```
class NetAppUMAggregate(object):
    ''' aggregates initialize and class methods '''

    def __init__(self):
        self.argument_spec = netapp_utils.na_um_host_argument_spec()
        self.module = AnsibleModule(
            argument_spec=self.argument_spec,
            supports_check_mode=True
        )
        if self.module._name in 'na_um_list_aggregates':
            self.module.deprecate(
                "The 'na_um_list_aggregates' module has been renamed to 'na_um_aggregates_info'",
                version='21.6.0', collection_name='netapp.um_info')

        self.na_helper = NetAppModule()
        self.parameters = self.na_helper.set_parameters(self.module.params)

        self.rest_api = UMRestAPI(self.module)
```

I get the following error, what do i need to do to get around this?

ERROR: Found 5 pylint issue(s) which need to be resolved:

ERROR: plugins/modules/na_um_aggregates_info.py:123:12: collection-deprecated-version: Deprecated version ('21.6.0') found in call to Display.deprecated or AnsibleModule.deprecate

ERROR: plugins/modules/na_um_clusters_info.py:112:12: collection-deprecated-version: Deprecated version ('21.6.0') found in call to Display.deprecated or AnsibleModule.deprecate

ERROR: plugins/modules/na_um_nodes_info.py:105:12: collection-deprecated-version: Deprecated version ('21.6.0') found in call to Display.deprecated or AnsibleModule.deprecate

ERROR: plugins/modules/na_um_svms_info.py:134:12: collection-deprecated-version: Deprecated version ('21.6.0') found in call to Display.deprecated or AnsibleModule.deprecate

ERROR: plugins/modules/na_um_volumes_info.py:93:12: collection-deprecated-version: Deprecated version ('21.6.0') found in call to Display.deprecated or AnsibleModule.deprecate

**Comment by lonico** [comment]
I wonder if you need something like
https://github.com/ansible-collections/community.crypto/blob/201920d161fb68dc83de8d37e5b832092b135c42/meta/runtime.yml

**Comment by felixfontein** [comment]
Two things:

1. `self.module._name in 'na_um_list_aggregates'` will only be true if `self.module._name` is one of the letters `n`, `a`, `_`, .... You want `self.module._name in ('na_um_list_aggregates', )` instead. Even better, also list the FQCN in there: `self.module._name in ('na_um_list_aggregates', 'netapp.um_info.na_um_list_aggregates')`.
2. The `version` parameter of `self.module.deprecate` should be the version when whatever that has been deprecated will be removed. I guess you already updated galaxy.yml's version to `21.6.0`, so the sanity checks basically tell you it's about time to remove this. You probably want to use `version='23.0.0'` or something like that (it needs to be a major release because of semver, and `23.0.0` gives your customers more time to adjust than `22.0.0`, but in the end you have to decide :) ).

**Comment by felixfontein** [comment]
This: https://github.com/ansible-collections/community.crypto/blob/201920d161fb68dc83de8d37e5b832092b135c42/meta/runtime.yml#L14-L17 can also be done instead of adding the `self.module.deprecate` call, but it will not work with Ansible 2.9, only with ansible-base 2.10 and ansible-core 2.11+. So if you have users of your collection that are using Ansible 2.9, they might only find out that the module has been renamed when the old name is finally removed and their playbooks/roles stop working.

**Comment by carchi8py** [comment]
1. was an old change we've already switched this to self.module._name in ('na_um_list_aggregates', 'netapp.um_info.na_um_list_aggregates') internally. 

2. If i've made na_um_list_aggregates.py a sim link of na_um_aggregates_info.py and i add self.module.deprecate version='23.0.0' that going to appear in the documentation for both. I'll need to make a copy of the file (and not a sim-link for the documentation to be correct).

**Comment by carchi8py** [comment]
@felixfontein , @tadeboro  Before we make 21.6.0 the change were push out from bitbucket to github about an hour, we had to do it in 2 part. I'll be rolling out 21.6.0 either later today or early tomarrow. 

https://github.com/ansible-collections/netapp/commit/4d48a01c9e63565d3131045e0dd121f5ba4817a2#diff-ed78f6031f9eed6d376fa4594c2e68939a4a2dbebd9c85b1da99ed3dfd7894a3

https://github.com/ansible-collections/netapp/commit/3f91cbaceee7c17d9cf9bc08ef3b269bc8594004#diff-ed78f6031f9eed6d376fa4594c2e68939a4a2dbebd9c85b1da99ed3dfd7894a3

**Comment by felixfontein** [comment]
@carchi8py a quick comment: I would note in the `description:` of every module that it has been renamed in version 21.6.0 of your collection from `<oldname>` to `<newname>` and that the functionality did not change. This makes users more confident to just chnage the module name in their roles/playbooks.

**Comment by carchi8py** [comment]
@felixfontein  i added a comment in the doc fragment (that added to all modules) with a message in the notes sections.
https://github.com/ansible-collections/netapp/blob/main/ansible_collections/netapp/um_info/plugins/doc_fragments/netapp.py#L56

We pushed out 20.6.0 (If we need to move this from the note section to the description section let me know and i'll make a 20.6.1 in the morning.

**Comment by lonico** [comment]
Modules have been renamed as _info and older modules are deprecated.

https://github.com/ansible-collections/netapp.um_info/tree/main/plugins/modules
